### ISSUE TITLE
php-composter doesn't honour the containing project's vendor-dir config

### ISSUE THREAD

**Issue by javorszky** [php-composter/php-composter#10]
project's `composer.json` has this in it:
```
...
  "config": {
    "vendor-dir": "wp-content/vendor"
  },
...
```
the package still assumes that the vendor directory is at the root.

I've added a `die($composterTemplate);` [here](https://github.com/php-composter/php-composter/blob/master/src/Plugin.php#L168):

## actual
Does not exist in the filesystem
```
/Users/javorszky/Sites/<clientsite>/vendor/php-composter/php-composter/includes/
```
## expected 
Exists in the filesystem
```
/Users/javorszky/Sites/<clientsite>/wp-content/vendor/php-composter/php-composter/includes/
```

**Comment by javorszky** [comment]
So just figured out that even the current config file is behind the autoload path... 

got caught up in other work, but currently trying to wrap this up

**Comment by javorszky** [comment]
https://github.com/javorszky/php-composter/commit/cbf05cb28bc66f1fd41028b17a4658fa8ca07957 solves the issue of the composer path, however I'm now running into the following problem:

```
PHP Fatal error:  Uncaught Error: Class 'Composer\IO\ConsoleIO' not found in /Users/javorszky/Sites/php-composter/src/BaseAction.php:98
Stack trace:
#0 /Users/javorszky/Sites/php-composter/src/BaseAction.php(86): PHPComposter\PHPComposter\BaseAction->getDefaultConsoleIO()
#1 /Users/javorszky/Sites/php-composter/includes/bootstrap.php(54): PHPComposter\PHPComposter\BaseAction->__construct('pre-commit', '/Users/javorszk...')
#2 {main}
  thrown in /Users/javorszky/Sites/php-composter/src/BaseAction.php on line 98
```
I'm not sure this is related to the changes... it doesn't look like this should happen.

I've deleted the vendor directory, ran `composer install`, ran `composer update`, tried all variations to no succcess.
